### ISSUE TITLE
New Chip Addition: ASM1051

### ISSUE THREAD

**Issue by u2n** [themaddoctor/linux-mybook-tools#9]
If themaddoctor were *really* mad, wouldn't he want to **add support for the ASMedia 1051**?  (You must be mad!)

After trying reallymine -- without success; no surprise as ASM-anything is not supported -- gave this method a shot. First tried the Appendix E script to get the keyblock, a fail, as expected.

Next, remembered **testdisk** was installed so let it do a scan and, **amazingly, it found and recovered nearly every single file** (numbering 1.4M and climbing), though the directory structure was somewhat mangled.

So WTH? My testdisk v.7.0 dates to 2015, about the same as the (4TB My Book) drive recovered. The program is clearly able to decrypt at the file level so the keyblock location and decryption algorithm must be in the [source](https://www.cgsecurity.org/mw/index.php?title=TestDisk&action=edit), which is open.

But **the method here is superior because it leaves the directory structure intact**. So wanting to make a contribution to the effort, I used hddsupertool to export all the firmware modules, attached. This is from the bare drive previously encrypted with the ASM1051w board. Hope it helps.

**EDIT**
.zip attachments get stripped off. Will put this in a repo tomorrow.

**Comment by themaddoctor** [comment]
I don't believe that your disk was encrypted (at least not as seen by software). Testdisk doesn't know about these things, anyway. I've talked to people about this chip before.

If you want to be sure, try dumping the first 2 MB from the bare drive and upload it here. I'll look at it.

**Comment by u2n** [comment]
On further checking, maddoc, you are absolutely correct. The Internet clogged with encryption posts, when the disk refused to mount and a review of the start data showed nothing useful, my assumption -- wrong, as it turns out -- was that the troubles were encryption-induced.

You knew that testdisk doesn't decrypt so the giveaway is finding that testdisk recovered the files. Actually, I'm almost disappointed. :^)

So closing this issue now, thank you, but also documenting here that if the ASM1051 chip is found, the data on disk is likely in the clear.

...Ok, and should also mention the REASON the disk won't mount (which is what brought me here). Windows (an OS that has no practical reason for existence) corrupts superblocks by writing in a bad physical device size.

In my case, for example, the true physical size is "976746454 4k blocks," which is 7813971635 512-B sectors, or 4000753476096 bytes. Windows updated ALL the superblock copies with 536870911 blocks. This number, having no bearing on reality, effectively prevents the disk from mounting ('Filesystem larger than device' error).

Superblock filesystem size descriptors are easily changed, but device size descriptors not. So the only two methods I've found that (reportedly) work are:
- Make a disk image, then re-size that image (by cutting off from the end) to match the filesystem size.
- Edit the superblock directly, making both sizes match. (But have found no tool or template to do this yet.)

So these are my findings; please correct as needed.

**Comment by gns1l** [comment]
The USB bridge of one of my 3TB WD Elements drive also contains an Asmedia chip. The PCB is equal to one with the JMicron chip except it has this ASM1051W chip. The drive is from Jan 2014.

The start of the drive does not look to be encrypted, but still I cannot mount the drive without using the WD usb bridge PCB.
A different make of usb bridge and also direct SATA connection give similar failure results.

As I am only using Linux and the drive has an ext4 filesystem, I do not believe these problems are caused by Windows.

With the WD usb bridge PCB, lsusb gives:
ID 1058:107c Western Digital Technologies, Inc. Elements Desktop (WDBWLG)

cat /proc/partitions gives:
   8       48 2930233344 sdd
   8       49 2930232320 sdd1

fdisk -l /dev/sdd:
Disk /dev/sdd: 2.7 TiB, 3000558944256 bytes, 732558336 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x00028375

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdd1         256 732558335 732558080  2.7T 83 Linux

file -s /dev/sdd:
/dev/sdd: DOS/MBR boot sector MS-MBR XP english at offset 0x12c "Invalid partition table" at offset 0x144 "Error loading operating system" at offset 0x163 "Missing operating system", disk signature 0x28375; partition 1 : ID=0x83, start-CHS (0x0,4,5), end-CHS (0x21f,165,6), startsector 256, 732558080 sectors


Connected via an Ewent usb3.0 bridge:
/proc/partinfo:
   8       48 2930266584 sdd
   8       49  366279040 sdd1

fdisk -l /dev/sdd
Disk /dev/sdd: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00028375

Device     Boot Start       End   Sectors   Size Id Type
/dev/sdd1         256 732558335 732558080 349.3G 83 Linux

file -s /dev/sdd
/dev/sdd: DOS/MBR boot sector MS-MBR XP english at offset 0x12c "Invalid partition table" at offset 0x144 "Error loading operating system" at offset 0x163 "Missing operating system", disk signature 0x28375; partition 1 : ID=0x83, start-CHS (0x0,4,5), end-CHS (0x21f,165,6), startsector 256, 732558080 sectors

mount /dev/sdd1 /mnt -t ext4 -o ro
mount: wrong fs type, bad option, bad superblock on /dev/sdd1,
       missing codepage or helper program, or other error

dmesg:
[62636.397240] usb 4-1: new SuperSpeed USB device number 11 using xhci_hcd
[62636.414073] usb 4-1: New USB device found, idVendor=abcd, idProduct=6103
[62636.414088] usb 4-1: New USB device strings: Mfr=4, Product=5, SerialNumber=6
[62636.414090] usb 4-1: SerialNumber: 20150126
[62636.415220] usb-storage 4-1:1.0: USB Mass Storage device detected
[62636.415687] scsi host16: usb-storage 4-1:1.0
[62637.413854] scsi host16: scsi scan: INQUIRY result too short (5), using 36
[62637.413861] scsi 16:0:0:0: Direct-Access     WDC WD30 EZRX-00SPEB0          PQ: 0 ANSI: 0
[62637.414433] sd 16:0:0:0: Attached scsi generic sg3 type 0
[62637.414608] sd 16:0:0:0: [sdd] Very big device. Trying to use READ CAPACITY(16).
[62637.414773] sd 16:0:0:0: [sdd] 5860533168 512-byte logical blocks: (3.00 TB/2.73 TiB)
[62637.415486] sd 16:0:0:0: [sdd] Write Protect is off
[62637.415491] sd 16:0:0:0: [sdd] Mode Sense: 3b 00 00 00
[62637.416226] sd 16:0:0:0: [sdd] No Caching mode page found
[62637.416230] sd 16:0:0:0: [sdd] Assuming drive cache: write through
[62637.416588] sd 16:0:0:0: [sdd] Very big device. Trying to use READ CAPACITY(16).
[62637.570385]  sdd: sdd1
[62637.571183] sd 16:0:0:0: [sdd] Very big device. Trying to use READ CAPACITY(16).
[62637.572743] sd 16:0:0:0: [sdd] Attached SCSI disk
[63925.224676] EXT4-fs (sdd1): VFS: Can't find ext4 filesystem
[64862.285861] NILFS: Can't find nilfs on dev sdd1.
[64887.912636] EXT4-fs (sdd1): VFS: Can't find ext4 filesystem

It seems that a different logical/physical sector size has now been used.


Next I tried to connect the drive to a SATA connector on the motherboard.


fdisk -l /dev/sdd
Disk /dev/sdd: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x00028375

Device     Boot Start       End   Sectors   Size Id Type
/dev/sdd1         256 732558335 732558080 349.3G 83 Linux

Now only the logical sector size is different, the physical sector size is the same as with the WD usb bridge PCB.
However it is still not possible to mount the drive:

mount /dev/sdd1 /mnt
mount: wrong fs type, bad option, bad superblock on /dev/sdd1,
       missing codepage or helper program, or other error

dmesg:
[    1.200762] ata3.00: ATA-9: WDC WD30EZRX-00SPEB0, 80.00A80, max UDMA/133
[    1.200793] ata3.00: 5860533168 sectors, multi 16: LBA48 NCQ (depth 31/32), AA

[    1.223231] scsi 2:0:0:0: Direct-Access     ATA      WDC WD30EZRX-00S 0A80 PQ: 0 ANSI: 5
[    1.223336] sd 2:0:0:0: [sdc] 5860533168 512-byte logical blocks: (3.00 TB/2.73 TiB)
[    1.223338] sd 2:0:0:0: [sdc] 4096-byte physical blocks
[    1.223355] sd 2:0:0:0: Attached scsi generic sg2 type 0
[    1.223404] sd 2:0:0:0: [sdc] Write Protect is off
[    1.223405] sd 2:0:0:0: [sdc] Mode Sense: 00 3a 00 00
[    1.223434] sd 2:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA


Is there a way to tell Linux that it should use a logical sector size of 4096 bytes?
Or would that still not help?

Thanks for any support or suggestions (and for the work with the other chips)

**Comment by themaddoctor** [comment]
You might have to use fuse-ext4 to mount it, since the linux kernel only allows block sizes that are <= a page size or something like that.

This will tell you if the filesystem is where it should be:
sudo dd if=/dev/sdd skip=2048 count=64 | file -

If you get a positive result, try a loop device (see the last few pages of my PDF), first with the kernel's ext4 driver, then if that fails, with fuse-ext4.

Let me know if it works.

**Comment by u2n** [comment]
Very interested in these results also.

To clarify, the disk was only connected when Win 10 was booted - I'd read that's all it takes. (Pardon if I wrongly blamed Windows. It's still a POS OS IMO.)

Your drive is accessible through both SATA and USB interfaces; mine is only via SATA. On manually resizing the FS to match the device size (to get rid of the mismatch error), new errors sprang up about missing or incorrect bitmaps. These are low-level FS descriptors in the superblock that get "corrupted" by the bridge, I read. And apparently it's so difficult to re-code them manually, no one even tries.

Honestly, though, if the fuse-ext4 mount doesn't work, it's really easy to just let testdisk copy the FS to a new disk. One tip: Get a target disk that's bigger than the source disk. The recovered FS will be bigger than the original.

**Comment by gns1l** [comment]
Success!

The results as obtained using the Ewent usb bridge:
sudo if=/dev/sdd skip=2048 count=64 | file -
64+0 records in
64+0 records out
32768 bytes (33 kB, 32 KiB) copied, 0.00129485 s, 25.3 MB/s
/dev/stdin: Linux rev 1.0 ext4 filesystem data, UUID=bc289de9-b9c0-4a1f-a7c9-c881b08985dd, volume name "MyBook3" (extents) (large files) (huge files)

fdisk -s /dev/sdd
2930266584

The instructions in the pdf for mounting with a loop device did not work for me as they assume that you have an image file "wd" and use "/dev/mapper/wd".
Using kpartx -a /dev/sdd to map the partition probably works; fdisk -s /dev/mapper/sdd1 then gave 366279040 as a result.
But when I read the man-files I hoped it could be done in a more straight-forward manner.
The OS already knew about the partition, so the mapper did not seem necessary.

So I tried:
sudo mount /dev/sdd /mnt/wd -o loop,offset=1048576
and the partition was mounted without any complaints.

df shows:
/dev/loop0     2884121824 2819494964   6005832 100% /mnt/wd

So the whole partition, directories and files can now be accessed without problems!

Thank you for the trick with the offset and the loop device.
Now at least I know that the files can also be used without the WD usb bridge,   

The only remaining question for me is how to find out which offset to use when more partitions are present.

**Comment by themaddoctor** [comment]
Congrats.

I suspect that if more partitions are present, then you could read the partition table and multiple all of the numbers by 8.

Knowing that, you can now run fdisk and rebuild the table so that it works the way you want.

**Comment by gns1l** [comment]
Thanks,

I had another drive with 2 partitions and it appeared to have also an Asmedia 1051W chip.
So I calculated the offset from the startsector of the partition as given by fdisk, knowing that the sectors in fdisk are 4096 bytes (instead of 512), and with that offset I could also succesfully mount the second partition.
I wil not try to modify the partition table for the moment as I will put this drive back in its WD enclosure.

**Comment by themaddoctor** [comment]
You're welcome.
